import {useState,useRef} from 'react';
export default function App(){
 const [pin,setPin]=useState(''),[ok,setOk]=useState(false);
 const [clientes,setClientes]=useState([]),[nome,setNome]=useState(''),[tel,setTel]=useState('');
 const [pacote,setPacote]=useState('Essencial'),[ativo,setAtivo]=useState(null),[obs,setObs]=useState('');
 const ref=useRef(null);const totais={Essencial:3,'Ativação':6,Continuidade:9,Anual:24};
 if(!ok)return <div className='login'><h1>OCCHY</h1><p>Passaporte Digital</p><input type='password' maxLength='6' value={pin} onChange={e=>setPin(e.target.value)} placeholder='PIN'/><button onClick={()=>pin==='123456'&&setOk(true)}>Entrar</button></div>;
 if(ativo!==null){const c=clientes[ativo];return <div className='app'><button className='back' onClick={()=>setAtivo(null)}>← Voltar</button><h2>{c.nome}</h2><p>{c.pacote} • {c.usadas}/{c.total}</p><textarea placeholder='Observação da sessão' value={obs} onChange={e=>setObs(e.target.value)} rows='3'/><canvas ref={ref} width='360' height='140' style={{width:'100%',background:'#111',borderRadius:'16px'}} onPointerDown={e=>{const x=e.nativeEvent.offsetX,y=e.nativeEvent.offsetY,ctx=ref.current.getContext('2d');ctx.strokeStyle='#E8E1D8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);const mv=f=>{ctx.lineTo(f.offsetX,f.offsetY);ctx.stroke()};const up=()=>{ref.current.onpointermove=null;window.onpointerup=null};ref.current.onpointermove=f=>mv(f.nativeEvent);window.onpointerup=up;}}/><button className='novo' onClick={()=>{const n=[...clientes];if(n[ativo].usadas<n[ativo].total){n[ativo].usadas++;n[ativo].historico=[...(n[ativo].historico||[]),{data:new Date().toLocaleDateString('pt-PT'),obs}];setClientes(n);setObs('');setAtivo(null)}}}>Concluir Sessão</button><div className='lista'>{(c.historico||[]).slice().reverse().map((h,i)=><div className='cliente' key={i}><div><h3>Sessão {c.historico.length-i}</h3><span>{h.data}</span><p>{h.obs}</p></div></div>)}</div></div>}
 return <div className='app'><header><h1>OCCHY</h1><p>Passaporte Digital</p></header><div className='card'><input placeholder='Nome da cliente' value={nome} onChange={e=>setNome(e.target.value)}/><input placeholder='WhatsApp' value={tel} onChange={e=>setTel(e.target.value)}/><select value={pacote} onChange={e=>setPacote(e.target.value)}><option>Essencial</option><option>Ativação</option><option>Continuidade</option><option>Anual</option></select><button className='novo' onClick={()=>{if(!nome.trim())return;setClientes([{nome,telefone:tel,pacote,total:totais[pacote],usadas:0,historico:[]},...clientes]);setNome('');setTel('');}}>+ Nova Cliente</button></div><div className='lista'>{clientes.length===0?<div className='cliente'><div><h3>Nenhuma cliente cadastrada</h3><span>Começa pelo primeiro cadastro.</span></div></div>:clientes.map((c,i)=><div className='cliente' key={i}><div><h3>{c.nome}</h3><span>{c.pacote} • {c.usadas}/{c.total}</span></div><button className='sessao' onClick={()=>setAtivo(i)}>Abrir</button></div>)}</div><nav><span>Clientes</span><span>Hoje</span><span>Perfil</span></nav></div>
}